CREATE OR REPLACE PROCEDURE INSERTION_OF_TABLES
AS
BEGIN
    
    INSERT INTO SUPPLIER (SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL)
    SELECT 
        DISTINCT SUPPLIER_NAME, 
        MAX(SUPP_CONTACT_NAME) AS SUPP_CONTACT_NAME,
        MAX(SUPP_ADDRESS) AS SUPP_ADDRESS,
        MAX(SUPP_CONTACT_NUMBER) AS SUPP_CONTACT_NUMBER,
        MAX(SUPP_EMAIL) AS SUPP_EMAIL
    FROM XXBCM_ORDER_MGT
    GROUP BY SUPPLIER_NAME;

    -- Insert into ORDER_MAIN table
    INSERT INTO ORDER_MAIN (ORDER_REF, ORDER_DATE, ORDER_TOTAL_AMOUNT, ORDER_STATUS, ORDER_DESCRIPTION, SUPPLIER_ID)
    SELECT DISTINCT 
        SUBSTR(ORDER_REF, 1, 5) AS ORDER_REF,
        ORDER_DATE,
        ORDER_TOTAL_AMOUNT,
        ORDER_STATUS,
        ORDER_DESCRIPTION,
        (SELECT MAX(SUPPLIER_ID) FROM SUPPLIER WHERE SUPPLIER_NAME = XXBCM_ORDER_MGT.SUPPLIER_NAME)
    FROM XXBCM_ORDER_MGT
    WHERE ORDER_TOTAL_AMOUNT IS NOT NULL
    AND ORDER_STATUS NOT IN ('Received', 'Cancelled');

    -- Insert into ORDER_LINE table
    INSERT INTO ORDER_LINE (ORDER_REF, ORDER_DATE, ORDER_LINE_AMOUNT, ORDER_STATUS, ORDER_DESCRIPTION, ORDER_PARENT_REF)
    SELECT ORDER_REF,
           ORDER_DATE,
           ORDER_LINE_AMOUNT,
           ORDER_STATUS,
           ORDER_DESCRIPTION, 
           SUBSTR(ORDER_REF, 1, 5) AS ORDER_PARENT_REF
    FROM XXBCM_ORDER_MGT
    WHERE ORDER_REF LIKE '%-%';

    -- Insert into INVOICES_NUMBER table
    INSERT INTO INVOICES_NUMBER (INVOICE_DATE, INVOICE_REF, INVOICE_STATUS, INVOICE_DESCRIPTION, INVOICE_HOLD_REASON, INVOICE_AMOUNT, ORDER_ID, ORDER_PARENT_REF)
    SELECT 
        INVOICE_DATE,
        INVOICE_REFERENCE,
        INVOICE_STATUS,
        INVOICE_DESCRIPTION,
        INVOICE_HOLD_REASON,
        INVOICE_AMOUNT,
        (SELECT DISTINCT ORDER_ID 
         FROM ORDER_LINE 
         WHERE ORDER_REF = X.ORDER_REF 
         AND ROWNUM = 1),
        SUBSTR(ORDER_REF, 1, 5) AS ORDER_PARENT_REF
    FROM XXBCM_ORDER_MGT X
    WHERE X.ORDER_REF LIKE '%-%';

  
    DBMS_OUTPUT.PUT_LINE('Migration complete');
    
END;
/